image: sensirion/python

stages:
  - test
  - build
  - deploy

variables:
  PACKAGE_NAME: "sgpxx"

test:
  stage: test
  tags:
    - linux
    - docker
  script:
    - apt-get update && apt-get install -y linux-headers-generic
    - export KERNELDIR=/lib/modules/$(uname -r)/build/
    - ${KERNELDIR}/scripts/checkpatch.pl -no-tree -f --strict sgpxx/sgpxx.c
    - make clean && make

build:
  stage: build
  tags:
    - linux
    - docker
  only:
    - master
  script:
    - echo "Create snapshot artifact"
  artifacts:
    expire_in: 1 week
    name: ${PACKAGE_NAME}-${CI_COMMIT_REF_NAME}
    paths:
      - LICENSE
      - Makefile
      - README
      - sgpxx/

deploy:
  stage: deploy
  tags:
    - linux
    - docker
  only:
    - tags
  script:
    - echo "Create release artifact"
  artifacts:
    name: ${PACKAGE_NAME}-${CI_COMMIT_TAG}
    paths:
      - LICENSE
      - Makefile
      - README
      - sgpxx/

